const prompts = [
    "You wake up one morning with a metalic taste in your mouth. Your palms are a crimson red and sticky...",
    "The cold mountain air billows as you take another step forward...",
    "I'm pretty adventurous when it comes to food, but I'd never eat _____",
    "The fire crackles in the night sky. You can see the stars peeking through the treetops. You hear a rustle in the bushes...",
    "\"Aha! I knew you were the one who was behind it all!\"...",
    "Every step takes me further and further away from my friends, my family, my world. I can't stop now...",
    "The one thing they drill into you at farming school is to NEVER ______",
    "What is something you've always wanted to do, but have been too afraid to?",
    "I don't believe in ghosts, but I could never explain what I saw that night last summer...",
    "The walls of the house sigh as you step through the door and onto the abused wooden floorboards.",
    "What's your most cherished memory from your childhood?",
    "If you never had to work again, what would you be doing right now?",
    "I couldn't tell her how I felt. I saw her on the street yesterday, and my stomach hurt...",
    "He's everything I ever wanted, but his friends keep telling me to be careful...",
    "I would take a bullet for them. I love them with all my heart. They make life worth living...",
    "I can't go back to that bar anymore...",
    "How many times do I have to say it? I am not quitting my job to hunt treasure with you...",
    "The bic lighter's paltry flame flickered in the October breeze. It was all we could do to see each other...",
    "I will never forget the day I became a man...",
    "I never thought I'd be the first person to walk on Mars...",
    "Growing up, there was always something odd about that Jacob kid next door. He never came out to play with the rest of us. Sometimes I forget he was even there...",
    "\"Last night was wild bro! You remember what happened, right?\"",
    "Cindy looked up at ne. Her eyes welled with tears. \"We need to talk\". My heart fell to the ground and shattered.",
    "Who is the one person in the world you admire the most?",
    "If you only had one more day to live, how would you spend it?",
    "If you could travel to anywhere in the world right now, where would that be?",
    "My twenties were a frenetic blur. If I could tell you about the things I did...",
    "As I lay here with the cold hand of death on my shoulder, there's only one thing I regret...",
    "What is the most absurd thing you can think of right now? Write a story about it.",
    "If you could travel through time, when would you want to visit the most?",
    "What are you procrastinating from right now? I mean, why else would you be here?",
    "Today's the day! We are starting our multi-million dollar business...",
    "What makes you unique?",
    "If you could have any superpower, what would you pick?",
    "\"Just keep pushing! You're almost there!\"...",
    "If I ever see your face in this town again. I'll run you out myself...",
    "The din of the starlit night was yanked away by the blare of an engine...",
    "The trees slumped over along the path. A canopy wavered in the breeze...",
    "What would your ideal day be?",
    "If you could only eat one thing for the rest of your life, what would it be?",
    "The turbulent waves slapped the sides of our poor, little canoe. We were miles away from the shoreline...",
    "Have you ever done something that you've immediately regretted? What was it?",
    "Do you have any fears?",
    "Tell me about that annoying friend or coworker that you really need to vent about.",
    "What's going on in your life right now? What's an average day like for you?",
]

export default prompts;